version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/


  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    depends_on:
      - frontend
    env_file:
      - ./.env

  backend:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
      # Когда будешь писать воркфлоу для гитхаба,
      # секцию build нужно будет удалить и заменить на что-то вида
      # image: ТВОЙ_ЮЗЕРНЭЙМ_НА_ДОКЕРХАБЕ/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env


  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
      - backend


volumes:
  postgres_data:
  static_value:
  media_value:
  
