# Generated by Django 4.2.1 on 2023-06-03 10:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#0000FF', 'Синий'), ('#FFA500', 'Оранжевый'), ('#008000', 'Зеленый'), ('#800080', 'Фиолетовый'), ('#FFFF00', 'Желтый'), ('#6F4E37', 'Кофе и кофеные напитки')], default='##0000FF', help_text='Имя тега', image_field=None, max_length=18, samples=None, verbose_name='Название'),
        ),
    ]
