# Generated by Django 4.2.1 on 2023-06-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.PositiveSmallIntegerField(help_text='Имя тега', max_length=250, unique=True, verbose_name='Название'),
        ),
    ]
