# Generated by Django 4.1.7 on 2023-03-29 14:39

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(max_length=200, verbose_name="единица измерения"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=200, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#FFFFFF",
                image_field=None,
                max_length=7,
                null=True,
                samples=None,
                verbose_name="цвет",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=200, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(
                max_length=200,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^[-а-я-a-zA-Z0-9_]+$")
                ],
                verbose_name="слаг",
            ),
        ),
    ]
